name: Сборка и публикация релиза

# Триггер: запускать этот рабочий процесс только при создании нового релиза
on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Получение исходного кода
        uses: actions/checkout@v4

      - name: 2. Настройка PHP и Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, curl, json
          tools: composer:v2

      # --no-dev: не устанавливать пакеты для разработки (типа phpunit, psalm)
      # --optimize-autoloader: создает оптимизированный автозагрузчик для лучшей производительности
      - name: 3. Установка зависимостей (composer install)
        run: composer install --no-dev --optimize-autoloader

      - name: 4. Создание и подготовка директории для сборки
        run: |
          # Создаем чистую папку для нашего релиза
          mkdir release_build
          mkdir -p release_build/vendor/digitalstars/simplevk
          cp -r src bin autoload.php release_build/vendor/digitalstars/simplevk/
          cp -r vendor/* release_build/vendor/
          cp LICENSE release_build/

      # Внедряем вызов PackagistReporter в файл Compatibility.php, который уже лежит в папке для сборки
      - name: 5. Внедрение кода для отправки статистики
        run: |
          REPORTER_PATH="release_build/vendor/digitalstars/simplevk/src/Compatibility.php"
          REPORTER_CODE='// Активация репортера для CI-сборки\nif (is_file(__DIR__ . \"/Utils/PackagistReporter.php\")) {\n    require_once __DIR__ . \"/Utils/PackagistReporter.php\";\n    \\DigitalStars\\SimpleVK\\Utils\\PackagistReporter::checkAndReport();\n}'
          # Вставляем код после 4-й строки (после use ...)
          sed -i '4a\'"$REPORTER_CODE" "$REPORTER_PATH"

      - name: 6. Подготовка к архивации
        id: prep
        run: |
          # Готовим имя для будущего архива
          echo "ARCHIVE_NAME=SimpleVK-${{ github.event.release.tag_name }}.zip" >> $GITHUB_ENV

      # Создаем ZIP-архив из содержимого подготовленной папки release_build
      - name: 7. Создание ZIP-архива
        run: |
          # Переходим в директорию сборки, чтобы в архиве не было родительской папки release_build
          cd release_build
          # Архивируем всё её содержимое
          zip -r ../${{ env.ARCHIVE_NAME }} .

      - name: 8. Загрузка архива в релиз
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/zip